# Use an official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app


COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# Copy all files into the container
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install fastapi uvicorn sqlalchemy python-dotenv pydantic passlib bcrypt email-validator python-multipart

# Expose the port
EXPOSE 8000

# Start the server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
