# Use an official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Upgrade pip and install dependencies early for caching
COPY requirement.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirement.txt

# Copy all source files into the container
COPY . .

# Expose the FastAPI port
EXPOSE 8000

# Run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
