version: '3.8'

services:
  backend:
    build: .
    container_name: capstone_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:12345@db/capstone_project
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: capstone_project
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
